# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

# .github/workflows/labeler.yml
name: PR Labeler
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Label PRs
      uses: actions/github-script@v5
      with:
        script: |
          const { github } = require("@actions/github");
          const ctx = github.context;
          const prNumber = ctx.payload.pull_request.number;
          const prTitle = ctx.payload.pull_request.title;
          const prBody = ctx.payload.pull_request.body;

          if (prTitle.includes("feat") || prBody.includes("feat")) {
            await github.rest.issues.addLabels({
              owner: ctx.repo.owner,
              repo: ctx.repo.repo,
              issue_number: prNumber,
              labels: ["enhancement"]
            });
          }
